#ifndef SYSTEM_PROGRAMMING_LEARNING_LABORATORY_WORK_6_6_2_MESSAGE_H_
#define SYSTEM_PROGRAMMING_LEARNING_LABORATORY_WORK_6_6_2_MESSAGE_H_

#define MATRIX_DIMENSION 4

struct message
{
    long type;
    char data[16];
};

#endif //SYSTEM_PROGRAMMING_LEARNING_LABORATORY_WORK_6_6_2_MESSAGE_H_
